algoritmo "Nome do Programa"
// 31 - Crie um programa usando o "PARA" que conte quantos números pares e ímpares existem entre 1 e 100.
var
numero, contadorPar, contadorImpar: inteiro

inicio

para numero de 1 ate 100 faca
se numero mod 2 = 0 entao
contadorPar<- contadorPar + 1
senao
contadorImpar<- contadorImpar + 1
fimse
fimpara
escreval("Quantidas de Pares: ",contadorPar)
escreva("Quantidas de Ímpares: ",contadorImpar)
fimalgoritmo